services:
  database:
    image: postgres:16.2-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  development:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - database
